from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / 'fonte' / 'dados' / 'json'


def write_json(filename: str, payload: dict) -> None:
    path = DATA_DIR / filename
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


write_json('leagues.json', {
    'leagues': [
        {
            'id': 'l1',
            'name': 'Liga de Futebol Antifascista (LFA)',
            'slug': 'liga-de-futebol-antifascista',
            'description': 'Liga de futebol amador (Fut7) criada em 2022 para reunir times e pessoas em torno do futebol, da solidariedade e da luta antifeixista.',
            'founded_year': 2022,
            'country': 'Brasil',
            'website': 'https://github.com/renanbelem/wiki-lfa',
            'logo_url': '/logos/gerais/lfa.png',
            'created_at': '2022-01-01T00:00:00Z',
            'updated_at': '2026-07-23T00:00:00Z',
            'is_active': True,
        }
    ]
})

write_json('seasons.json', {
    'seasons': [
        {'id': 'season-2022-a', 'league_id': 'l1', 'name': 'Apertura 22', 'slug': 'apertura-22', 'year': 2022, 'semester': 'apertura', 'start_date': '2022-03-01', 'end_date': '2022-06-30', 'status': 'finalizada', 'description': 'Primeira temporada da LFA em 2022.', 'banner_url': '/banners/2022-apertura.jpg', 'created_at': '2022-03-01T00:00:00Z', 'updated_at': '2022-07-01T00:00:00Z'},
        {'id': 'season-2022-c', 'league_id': 'l1', 'name': 'Clausura 22', 'slug': 'clausura-22', 'year': 2022, 'semester': 'clausura', 'start_date': '2022-07-01', 'end_date': '2022-10-31', 'status': 'finalizada', 'description': 'Segunda temporada da LFA em 2022.', 'banner_url': '/banners/2022-clausura.jpg', 'created_at': '2022-07-01T00:00:00Z', 'updated_at': '2022-11-01T00:00:00Z'},
        {'id': 'season-2023-a', 'league_id': 'l1', 'name': 'Apertura 23', 'slug': 'apertura-23', 'year': 2023, 'semester': 'apertura', 'start_date': '2023-03-01', 'end_date': '2023-06-30', 'status': 'finalizada', 'description': 'Temporada de 2023 com forte presença da Taça Cecília.', 'banner_url': '/banners/2023-apertura.jpg', 'created_at': '2023-03-01T00:00:00Z', 'updated_at': '2023-07-01T00:00:00Z'},
        {'id': 'season-2023-c', 'league_id': 'l1', 'name': 'Clausura 23', 'slug': 'clausura-23', 'year': 2023, 'semester': 'clausura', 'start_date': '2023-07-01', 'end_date': '2023-10-31', 'status': 'finalizada', 'description': 'Clausura de 2023.', 'banner_url': '/banners/2023-clausura.jpg', 'created_at': '2023-07-01T00:00:00Z', 'updated_at': '2023-11-01T00:00:00Z'},
        {'id': 'season-2024-a', 'league_id': 'l1', 'name': 'Apertura 24', 'slug': 'apertura-24', 'year': 2024, 'semester': 'apertura', 'start_date': '2024-03-01', 'end_date': '2024-06-30', 'status': 'finalizada', 'description': 'Temporada de 2024 com edição da Taça Cecília.', 'banner_url': '/banners/2024-apertura.jpg', 'created_at': '2024-03-01T00:00:00Z', 'updated_at': '2024-07-01T00:00:00Z'},
        {'id': 'season-2024-c', 'league_id': 'l1', 'name': 'Clausura 24', 'slug': 'clausura-24', 'year': 2024, 'semester': 'clausura', 'start_date': '2024-07-01', 'end_date': '2024-10-31', 'status': 'finalizada', 'description': 'Clausura de 2024.', 'banner_url': '/banners/2024-clausura.jpg', 'created_at': '2024-07-01T00:00:00Z', 'updated_at': '2024-11-01T00:00:00Z'},
        {'id': 'season-2025-a', 'league_id': 'l1', 'name': 'Apertura 25', 'slug': 'apertura-25', 'year': 2025, 'semester': 'apertura', 'start_date': '2025-03-01', 'end_date': '2025-06-30', 'status': 'finalizada', 'description': 'Taça Cecília 2025 Apertura e Copa Eric Cantona.', 'banner_url': '/banners/2025-apertura.jpg', 'created_at': '2025-03-01T00:00:00Z', 'updated_at': '2025-07-01T00:00:00Z'},
        {'id': 'season-2025-c', 'league_id': 'l1', 'name': 'Clausura 25', 'slug': 'clausura-25', 'year': 2025, 'semester': 'clausura', 'start_date': '2025-07-01', 'end_date': '2025-10-31', 'status': 'finalizada', 'description': 'Taça Cecília 2025 Clausura.', 'banner_url': '/banners/2025-clausura.jpg', 'created_at': '2025-07-01T00:00:00Z', 'updated_at': '2025-11-01T00:00:00Z'},
        {'id': 'season-2026-a', 'league_id': 'l1', 'name': 'Apertura 26', 'slug': 'apertura-26', 'year': 2026, 'semester': 'apertura', 'start_date': '2026-03-01', 'end_date': '2026-06-30', 'status': 'em_andamento', 'description': 'Temporada atual da LFA em 2026.', 'banner_url': '/banners/2026-apertura.jpg', 'created_at': '2026-02-01T00:00:00Z', 'updated_at': '2026-05-28T00:00:00Z'},
    ]
})

write_json('competitions.json', {
    'competitions': [
        {'id': 'comp-001', 'season_id': 'season-2025-a', 'name': 'Taça Cecília 2025 – Apertura', 'slug': 'taca-cecilia-2025-apertura', 'type': 'campeonato', 'format': 'turno_unico', 'start_date': '2025-03-01', 'end_date': '2025-06-30', 'status': 'finalizada', 'order': 1, 'description': 'Edição de 2025 da Taça Cecília, disputada em turno único com fase final mata-mata e campeão definido após pênaltis.', 'organizer': 'LFA', 'logo_url': '/logos/gerais/taca-cecilia.png', 'banner_url': '/banners/taca-cecilia.jpg', 'created_at': '2025-01-01T00:00:00Z', 'updated_at': '2025-07-01T00:00:00Z'},
        {'id': 'comp-002', 'season_id': 'season-2025-a', 'name': 'Copa Eric Cantona', 'slug': 'copa-eric-cantona', 'type': 'copa', 'format': 'eliminacao_direta', 'start_date': '2025-04-01', 'end_date': '2025-06-15', 'status': 'finalizada', 'order': 2, 'description': 'Copa dedicada à memória de Eric Cantona, disputada em formato eliminatório.', 'organizer': 'LFA', 'logo_url': '/logos/gerais/copa-cantona.png', 'banner_url': '/banners/copa-cantona.jpg', 'created_at': '2025-01-10T00:00:00Z', 'updated_at': '2025-06-16T00:00:00Z'},
        {'id': 'comp-003', 'season_id': 'season-2025-c', 'name': 'Taça Cecília 2025 – Clausura', 'slug': 'taca-cecilia-2025-clausura', 'type': 'campeonato', 'format': 'turno_unico', 'start_date': '2025-07-01', 'end_date': '2025-10-31', 'status': 'finalizada', 'order': 3, 'description': 'Segunda edição da Taça Cecília em 2025, vencida por Imperial.', 'organizer': 'LFA', 'logo_url': '/logos/gerais/taca-cecilia.png', 'banner_url': '/banners/taca-cecilia.jpg', 'created_at': '2025-06-01T00:00:00Z', 'updated_at': '2025-11-01T00:00:00Z'},
        {'id': 'comp-004', 'season_id': 'season-2026-a', 'name': 'Taça Cecília 2026 – Apertura', 'slug': 'taca-cecilia-2026-apertura', 'type': 'campeonato', 'format': 'turno_unico', 'start_date': '2026-03-01', 'end_date': '2026-06-30', 'status': 'em_andamento', 'order': 4, 'description': 'Edição atual da Taça Cecília em 2026, com classificação em andamento.', 'organizer': 'LFA', 'logo_url': '/logos/gerais/taca-cecilia.png', 'banner_url': '/banners/taca-cecilia.jpg', 'created_at': '2026-02-01T00:00:00Z', 'updated_at': '2026-05-28T00:00:00Z'},
        {'id': 'comp-005', 'season_id': 'season-2022-a', 'name': 'Taça Wladimir Rodrigues', 'slug': 'taca-wladimir-rodrigues', 'type': 'copa', 'format': 'eliminacao_direta', 'start_date': '2022-03-01', 'end_date': '2022-06-30', 'status': 'finalizada', 'order': 5, 'description': 'Competição de acesso e permanência da LFA, pensada como espaço de disputa e renovação.', 'organizer': 'LFA', 'logo_url': '/logos/gerais/taca-wladimir.png', 'banner_url': '/banners/taca-wladimir.jpg', 'created_at': '2022-02-01T00:00:00Z', 'updated_at': '2022-07-01T00:00:00Z'},
        {'id': 'comp-006', 'season_id': 'season-2023-c', 'name': 'Taça Sissi', 'slug': 'taca-sissi', 'type': 'copa', 'format': 'eliminacao_direta', 'start_date': '2023-07-01', 'end_date': '2023-10-31', 'status': 'finalizada', 'order': 6, 'description': 'Competição que homenageia Sissi e reforça o calendário da LFA.', 'organizer': 'LFA', 'logo_url': '/logos/gerais/taca-sissi.png', 'banner_url': '/banners/taca-sissi.jpg', 'created_at': '2023-06-01T00:00:00Z', 'updated_at': '2023-11-01T00:00:00Z'},
        {'id': 'comp-007', 'season_id': 'season-2024-a', 'name': 'Supertaça', 'slug': 'supertaca', 'type': 'copa', 'format': 'eliminacao_direta', 'start_date': '2024-03-01', 'end_date': '2024-03-15', 'status': 'finalizada', 'order': 7, 'description': 'Partida inaugural que define o primeiro grande campeão da temporada.', 'organizer': 'LFA', 'logo_url': '/logos/gerais/supertaca.png', 'banner_url': '/banners/supertaca.jpg', 'created_at': '2024-02-01T00:00:00Z', 'updated_at': '2024-03-16T00:00:00Z'},
        {'id': 'comp-008', 'season_id': 'season-2024-c', 'name': 'Copa Carlos Caszely', 'slug': 'copa-carlos-caszely', 'type': 'copa', 'format': 'eliminacao_direta', 'start_date': '2024-07-01', 'end_date': '2024-10-31', 'status': 'finalizada', 'order': 8, 'description': 'Copa dedicada ao legado de Carlos Caszely, com grande presença da torcida.', 'organizer': 'LFA', 'logo_url': '/logos/gerais/copa-caszely.png', 'banner_url': '/banners/copa-caszely.jpg', 'created_at': '2024-06-01T00:00:00Z', 'updated_at': '2024-11-01T00:00:00Z'},
        {'id': 'comp-009', 'season_id': 'season-2025-c', 'name': 'Copa Foice', 'slug': 'copa-foice', 'type': 'copa', 'format': 'eliminacao_direta', 'start_date': '2025-07-01', 'end_date': '2025-10-31', 'status': 'finalizada', 'order': 9, 'description': 'Competição emblemática da LFA ligada ao repertório político e cultural da liga.', 'organizer': 'LFA', 'logo_url': '/logos/gerais/copa-foice.png', 'banner_url': '/banners/copa-foice.jpg', 'created_at': '2025-06-20T00:00:00Z', 'updated_at': '2025-11-01T00:00:00Z'},
        {'id': 'comp-010', 'season_id': 'season-2026-a', 'name': 'Recopa', 'slug': 'recopa', 'type': 'copa', 'format': 'eliminacao_direta', 'start_date': '2026-03-01', 'end_date': '2026-06-30', 'status': 'em_andamento', 'order': 10, 'description': 'Recopa da LFA, reservada para os grandes campeões das principais competições.', 'organizer': 'LFA', 'logo_url': '/logos/gerais/recopa.png', 'banner_url': '/banners/recopa.jpg', 'created_at': '2026-02-01T00:00:00Z', 'updated_at': '2026-05-28T00:00:00Z'},
    ]
})

write_json('teams.json', {
    'teams': [
        {'id': '1', 'league_id': 'l1', 'name': 'CF Estrela Vermelha', 'slug': 'cf-estrela-vermelha', 'colors': '#dc2626', 'secondary_color': '#991b1b', 'abbreviation': 'CEV', 'founded_year': 2018, 'city': 'São Paulo', 'state': 'SP', 'logo_url': '/logos/teams/cf-estrela-vermelha.png', 'banner_url': '/banners/teams/cf-estrela-vermelha.png', 'description': 'Clube de futebol revolucionário com raízes comunitárias e histórico forte na LFA.', 'stadium_name': 'Campo da Revolução', 'president_name': 'Marcus Silva', 'coach_name': 'Diego Rojas', 'created_at': '2018-03-15T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '2', 'league_id': 'l1', 'name': 'Guairacá Futebol Ancestral', 'slug': 'guairaca-futebol-ancestral', 'colors': '#84cc16', 'secondary_color': '#65a30d', 'abbreviation': 'GFA', 'founded_year': 2020, 'city': 'Maringá', 'state': 'PR', 'logo_url': '/logos/teams/guairaca-futebol-ancestral.png', 'banner_url': '/banners/teams/guairaca-futebol-ancestral.png', 'description': 'Time ancestral que valoriza tradições, cultura popular e futebol comunitário.', 'stadium_name': 'Estádio Guairacá', 'president_name': 'Ana Tupi', 'coach_name': 'Carlos Tupinambá', 'created_at': '2020-01-10T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '3', 'league_id': 'l1', 'name': 'Deportivo Oriental', 'slug': 'deportivo-oriental', 'colors': '#0ea5e9', 'secondary_color': '#0284c7', 'abbreviation': 'DO', 'founded_year': 2019, 'city': 'Rio de Janeiro', 'state': 'RJ', 'logo_url': '/logos/teams/deportivo-oriental.png', 'banner_url': '/banners/teams/deportivo-oriental.png', 'description': 'Equipe orientada para o futebol solidário, com forte presença cultural e política.', 'stadium_name': 'Campo Oriental', 'president_name': 'Fernando Gómez', 'coach_name': 'Pablo Sánchez', 'created_at': '2019-05-20T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '4', 'league_id': 'l1', 'name': 'Sankara', 'slug': 'sankara', 'colors': '#f59e0b', 'secondary_color': '#d97706', 'abbreviation': 'SKR', 'founded_year': 2021, 'city': 'Brasília', 'state': 'DF', 'logo_url': '/logos/teams/sankara.png', 'banner_url': '/banners/teams/sankara.png', 'description': 'Time inspirado em ideais de autonomia, liberdade e solidariedade.', 'stadium_name': 'Arena Sankara', 'president_name': 'Zara Mendes', 'coach_name': 'Lionel Santos', 'created_at': '2021-02-14T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '5', 'league_id': 'l1', 'name': 'Primavera', 'slug': 'primavera', 'colors': '#ec4899', 'secondary_color': '#be185d', 'abbreviation': 'PRI', 'founded_year': 2022, 'city': 'Curitiba', 'state': 'PR', 'logo_url': '/logos/teams/primavera.png', 'banner_url': '/banners/teams/primavera.png', 'description': 'Time jovem, dinâmico e muito ligado ao renascimento do futebol popular.', 'stadium_name': 'Campo Primavera', 'president_name': 'Iris Fonseca', 'coach_name': 'Rafael Costa', 'created_at': '2022-03-01T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '6', 'league_id': 'l1', 'name': 'Teto Preto', 'slug': 'teto-preto', 'colors': '#1f2937', 'secondary_color': '#111827', 'abbreviation': 'TP', 'founded_year': 2017, 'city': 'Salvador', 'state': 'BA', 'logo_url': '/logos/teams/teto-preto.png', 'banner_url': '/banners/teams/teto-preto.png', 'description': 'Movimento de futebol de base em periferias com identidade forte.', 'stadium_name': 'Teto Preto Arena', 'president_name': 'Jorge Silva', 'coach_name': 'Marcelo Rocha', 'created_at': '2017-07-20T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '7', 'league_id': 'l1', 'name': 'Pé de Pano', 'slug': 'pe-de-pano', 'colors': '#6366f1', 'secondary_color': '#4f46e5', 'abbreviation': 'PP', 'founded_year': 2019, 'city': 'Recife', 'state': 'PE', 'logo_url': '/logos/teams/pe-de-pano.png', 'banner_url': '/banners/teams/pe-de-pano.png', 'description': 'Time que celebra a cultura popular, a rua e uma estética muito própria.', 'stadium_name': 'Arena Pé de Pano', 'president_name': 'Maria Gomes', 'coach_name': 'Felipe Torres', 'created_at': '2019-04-10T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '8', 'league_id': 'l1', 'name': 'Locomotiva Makhnovista F.S.C.', 'slug': 'locomotiva-makhnovista-fsc', 'colors': '#14b8a6', 'secondary_color': '#0d9488', 'abbreviation': 'LMF', 'founded_year': 2020, 'city': 'Porto Alegre', 'state': 'RS', 'logo_url': '/logos/teams/locomotiva-makhnovista-fsc.png', 'banner_url': '/banners/teams/locomotiva-makhnovista-fsc.png', 'description': 'Time que propaga ideais libertários e modos de organização coletiva.', 'stadium_name': 'Estádio da Locomotiva', 'president_name': 'Mikhail Petrov', 'coach_name': 'Alexei Romanov', 'created_at': '2020-06-15T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '9', 'league_id': 'l1', 'name': 'Resistência Alviverde', 'slug': 'resistencia-alviverde', 'colors': '#10b981', 'secondary_color': '#059669', 'abbreviation': 'RAV', 'founded_year': 2021, 'city': 'Belo Horizonte', 'state': 'MG', 'logo_url': '/logos/teams/resistencia-alviverde.png', 'banner_url': '/banners/teams/resistencia-alviverde.png', 'description': 'Time que resiste e persiste pela democratização do futebol.', 'stadium_name': 'Arena da Resistência', 'president_name': 'Carla Alves', 'coach_name': 'Bruno Ferreira', 'created_at': '2021-08-25T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '10', 'league_id': 'l1', 'name': 'Azulão', 'slug': 'azulao', 'colors': '#3b82f6', 'secondary_color': '#1d4ed8', 'abbreviation': 'AZL', 'founded_year': 2018, 'city': 'Santos', 'state': 'SP', 'logo_url': '/logos/teams/azulao.png', 'banner_url': '/banners/teams/azulao.png', 'description': 'Grande força do futebol paulista com tradição comunitária.', 'stadium_name': 'Estádio Azulão', 'president_name': 'Gustavo Lima', 'coach_name': 'Ricardo Dias', 'created_at': '2018-09-10T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '11', 'league_id': 'l1', 'name': 'Bolchesítio', 'slug': 'bolchesitio', 'colors': '#ef4444', 'secondary_color': '#b91c1c', 'abbreviation': 'BOL', 'founded_year': 2019, 'city': 'São Gonçalo', 'state': 'RJ', 'logo_url': '/logos/teams/bolchesitio.png', 'banner_url': '/banners/teams/bolchesitio.png', 'description': 'Time de orientação revolucionária e futebol comunitário.', 'stadium_name': 'Campo Bolchevique', 'president_name': 'Lenin Costa', 'coach_name': 'Trotsky Silva', 'created_at': '2019-10-20T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '12', 'league_id': 'l1', 'name': 'Linha Esquerda FR', 'slug': 'linha-esquerda-fr', 'colors': '#8b5cf6', 'secondary_color': '#7c3aed', 'abbreviation': 'LEF', 'founded_year': 2021, 'city': 'Campinas', 'state': 'SP', 'logo_url': '/logos/teams/linha-esquerda-fr.png', 'banner_url': '/banners/teams/linha-esquerda-fr.png', 'description': 'Frente revolucionária dedicada ao futebol livre e à participação popular.', 'stadium_name': 'Estádio da Linha Esquerda', 'president_name': 'Camila Rocha', 'coach_name': 'Lucas Martins', 'created_at': '2021-01-30T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '13', 'league_id': 'l1', 'name': 'América de Calo', 'slug': 'america-de-calo', 'colors': '#f97316', 'secondary_color': '#ea580c', 'abbreviation': 'ADC', 'founded_year': 2024, 'city': 'Porto Alegre', 'state': 'RS', 'logo_url': '/logos/teams/america-de-calo.png', 'banner_url': '/banners/teams/america-de-calo.png', 'description': 'Equipe com forte vínculo com o futebol das periferias e o imaginário popular.', 'stadium_name': 'Arena Calo', 'president_name': 'Luan Silva', 'coach_name': 'Mateus Rocha', 'created_at': '2024-01-15T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '14', 'league_id': 'l1', 'name': 'Atleticomuna', 'slug': 'atleticomuna', 'colors': '#6366f1', 'secondary_color': '#4338ca', 'abbreviation': 'AMU', 'founded_year': 2022, 'city': 'Curitiba', 'state': 'PR', 'logo_url': '/logos/teams/atleticomuna.png', 'banner_url': '/banners/teams/atleticomuna.png', 'description': 'Time ligado à cultura do bairro e à organização coletiva.', 'stadium_name': 'Arena Muna', 'president_name': 'Thiago Nunes', 'coach_name': 'Eduardo Pires', 'created_at': '2022-04-10T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '15', 'league_id': 'l1', 'name': '9-Dedos', 'slug': '9-dedos', 'colors': '#111827', 'secondary_color': '#374151', 'abbreviation': '9DD', 'founded_year': 2021, 'city': 'Curitiba', 'state': 'PR', 'logo_url': '/logos/teams/9-dedos.png', 'banner_url': '/banners/teams/9-dedos.png', 'description': 'Equipe técnica, veloz e muito presente nas decisões da LFA.', 'stadium_name': 'Arena dos Nove', 'president_name': 'Bruno Nunes', 'coach_name': 'Gabriel Lessa', 'created_at': '2021-05-01T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '16', 'league_id': 'l1', 'name': 'Latinofuturista', 'slug': 'latinofuturista', 'colors': '#facc15', 'secondary_color': '#ca8a04', 'abbreviation': 'LTF', 'founded_year': 2023, 'city': 'São Paulo', 'state': 'SP', 'logo_url': '/logos/teams/latinofuturista.png', 'banner_url': '/banners/teams/latinofuturista.png', 'description': 'Time com identidade urbana e forte presença artística.', 'stadium_name': 'Campo Futurista', 'president_name': 'Ramon Cruz', 'coach_name': 'Gabriel Mello', 'created_at': '2023-02-18T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '17', 'league_id': 'l1', 'name': 'Liverpanças', 'slug': 'liverpancas', 'colors': '#0f766e', 'secondary_color': '#115e59', 'abbreviation': 'LVP', 'founded_year': 2022, 'city': 'Porto Alegre', 'state': 'RS', 'logo_url': '/logos/teams/liverpancas.png', 'banner_url': '/banners/teams/liverpancas.png', 'description': 'Equipe brasileira com identidade forte e espírito de coletividade.', 'stadium_name': 'Campo Liverpanças', 'president_name': 'João Vitor', 'coach_name': 'Marcio Nunes', 'created_at': '2022-06-20T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '18', 'league_id': 'l1', 'name': 'Paulo Freire', 'slug': 'paulo-freire', 'colors': '#7c3aed', 'secondary_color': '#5b21b6', 'abbreviation': 'PFR', 'founded_year': 2021, 'city': 'Recife', 'state': 'PE', 'logo_url': '/logos/teams/paulo-freire.png', 'banner_url': '/banners/teams/paulo-freire.png', 'description': 'Equipe voltada à educação popular e ao esporte comunitário.', 'stadium_name': 'Arena Paulo Freire', 'president_name': 'Cecília Lima', 'coach_name': 'Ramon Diniz', 'created_at': '2021-09-12T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '19', 'league_id': 'l1', 'name': 'Sem Fronteiras', 'slug': 'sem-fronteiras', 'colors': '#4f46e5', 'secondary_color': '#312e81', 'abbreviation': 'SFR', 'founded_year': 2022, 'city': 'Belo Horizonte', 'state': 'MG', 'logo_url': '/logos/teams/sem-fronteiras.png', 'banner_url': '/banners/teams/sem-fronteiras.png', 'description': 'Time que representa a pluralidade da LFA.', 'stadium_name': 'Campo Sem Fronteiras', 'president_name': 'Luiza Pereira', 'coach_name': 'Davi Nogueira', 'created_at': '2022-07-12T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '20', 'league_id': 'l1', 'name': 'Toque de Classe', 'slug': 'toque-de-classe', 'colors': '#f43f5e', 'secondary_color': '#be123c', 'abbreviation': 'TQC', 'founded_year': 2023, 'city': 'Salvador', 'state': 'BA', 'logo_url': '/logos/teams/toque-de-classe.png', 'banner_url': '/banners/teams/toque-de-classe.png', 'description': 'Equipe com forte presença ofensiva e dinâmica de jogo.', 'stadium_name': 'Arena Toque', 'president_name': 'André Costa', 'coach_name': 'Leandro Santos', 'created_at': '2023-04-30T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '21', 'league_id': 'l1', 'name': 'Diamante', 'slug': 'diamante', 'colors': '#64748b', 'secondary_color': '#475569', 'abbreviation': 'DMA', 'founded_year': 2022, 'city': 'Florianópolis', 'state': 'SC', 'logo_url': '/logos/teams/diamante.png', 'banner_url': '/banners/teams/diamante.png', 'description': 'Time com cara de competição e histórico consistente.', 'stadium_name': 'Arena Diamante', 'president_name': 'Neusa Garcia', 'coach_name': 'Mateus Dias', 'created_at': '2022-01-20T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '22', 'league_id': 'l1', 'name': 'Discaída', 'slug': 'discaida', 'colors': '#a3e635', 'secondary_color': '#65a30d', 'abbreviation': 'DIS', 'founded_year': 2021, 'city': 'Recife', 'state': 'PE', 'logo_url': '/logos/teams/discaida.png', 'banner_url': '/banners/teams/discaida.png', 'description': 'Equipe que mistura fervor popular e competitividade.', 'stadium_name': 'Campo Discaída', 'president_name': 'Mário Souza', 'coach_name': 'Juca Teixeira', 'created_at': '2021-07-10T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '23', 'league_id': 'l1', 'name': 'Brigada Lupicínia', 'slug': 'brigada-lupicinia', 'colors': '#fb923c', 'secondary_color': '#c2410c', 'abbreviation': 'BLP', 'founded_year': 2022, 'city': 'Porto Alegre', 'state': 'RS', 'logo_url': '/logos/teams/brigada-lupicinia.png', 'banner_url': '/banners/teams/brigada-lupicinia.png', 'description': 'Time com forte identidade política e competitiva.', 'stadium_name': 'Campo Lupicínia', 'president_name': 'Cláudia Pires', 'coach_name': 'Ruan Serra', 'created_at': '2022-09-10T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '24', 'league_id': 'l1', 'name': 'Baianos de Mauá', 'slug': 'baianos-de-maua', 'colors': '#eab308', 'secondary_color': '#a16207', 'abbreviation': 'BMA', 'founded_year': 2021, 'city': 'Mauá', 'state': 'SP', 'logo_url': '/logos/teams/baianos-de-maua.png', 'banner_url': '/banners/teams/baianos-de-maua.png', 'description': 'Equipe tradicional da LFA com forte presença de identidade regional.', 'stadium_name': 'Arena Mauá', 'president_name': 'Davi Santos', 'coach_name': 'Cauã Moreira', 'created_at': '2021-11-12T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '25', 'league_id': 'l1', 'name': 'Caos da Villa', 'slug': 'caos-da-villa', 'colors': '#f59e0b', 'secondary_color': '#92400e', 'abbreviation': 'CDV', 'founded_year': 2023, 'city': 'São Paulo', 'state': 'SP', 'logo_url': '/logos/teams/caos-da-villa.png', 'banner_url': '/banners/teams/caos-da-villa.png', 'description': 'Time com muita energia e presença marcante nas partidas.', 'stadium_name': 'Arena da Villa', 'president_name': 'Igor Lima', 'coach_name': 'João Falcão', 'created_at': '2023-03-05T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '26', 'league_id': 'l1', 'name': 'Delas', 'slug': 'delas', 'colors': '#f472b6', 'secondary_color': '#9d174d', 'abbreviation': 'DEL', 'founded_year': 2022, 'city': 'Rio de Janeiro', 'state': 'RJ', 'logo_url': '/logos/teams/delas.png', 'banner_url': '/banners/teams/delas.png', 'description': 'Equipe que valoriza a participação feminina e a diversidade no futebol.', 'stadium_name': 'Campo Das Delas', 'president_name': 'Beatriz Costa', 'coach_name': 'Rafaela Nunes', 'created_at': '2022-08-02T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '27', 'league_id': 'l1', 'name': 'Faixa Preta', 'slug': 'faixa-preta', 'colors': '#111827', 'secondary_color': '#1f2937', 'abbreviation': 'FXP', 'founded_year': 2021, 'city': 'Curitiba', 'state': 'PR', 'logo_url': '/logos/teams/faixa-preta.png', 'banner_url': '/banners/teams/faixa-preta.png', 'description': 'Equipe de forte presença técnica e muita disciplina tática.', 'stadium_name': 'Arena Faixa Preta', 'president_name': 'Renato Leal', 'coach_name': 'João Nascimento', 'created_at': '2021-04-03T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '28', 'league_id': 'l1', 'name': 'Ginga', 'slug': 'ginga', 'colors': '#06b6d4', 'secondary_color': '#0f766e', 'abbreviation': 'GIN', 'founded_year': 2022, 'city': 'São Paulo', 'state': 'SP', 'logo_url': '/logos/teams/ginga.png', 'banner_url': '/banners/teams/ginga.png', 'description': 'Time com forte conexão com a cultura popular e a criatividade no campo.', 'stadium_name': 'Arena Ginga', 'president_name': 'Pedro Nunes', 'coach_name': 'Rafael Marinho', 'created_at': '2022-05-07T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '29', 'league_id': 'l1', 'name': 'Matsubara', 'slug': 'matsubara', 'colors': '#84cc16', 'secondary_color': '#4d7c0f', 'abbreviation': 'MAT', 'founded_year': 2021, 'city': 'Campinas', 'state': 'SP', 'logo_url': '/logos/teams/matsubara.png', 'banner_url': '/banners/teams/matsubara.png', 'description': 'Equipe com identidade forte e presença antiga na LFA.', 'stadium_name': 'Campo Matsubara', 'president_name': 'Aline Rocha', 'coach_name': 'Tiago Pires', 'created_at': '2021-03-20T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '30', 'league_id': 'l1', 'name': 'São Bento', 'slug': 'sao-bento', 'colors': '#38bdf8', 'secondary_color': '#0369a1', 'abbreviation': 'SBE', 'founded_year': 2022, 'city': 'Santos', 'state': 'SP', 'logo_url': '/logos/teams/sao-bento.png', 'banner_url': '/banners/teams/sao-bento.png', 'description': 'Equipe ligada à tradição do futebol de bairro.', 'stadium_name': 'Arena São Bento', 'president_name': 'Marcos Pires', 'coach_name': 'Jorge Tavares', 'created_at': '2022-06-14T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '31', 'league_id': 'l1', 'name': 'Zapatista', 'slug': 'zapatista', 'colors': '#dc2626', 'secondary_color': '#b91c1c', 'abbreviation': 'ZAP', 'founded_year': 2023, 'city': 'Porto Alegre', 'state': 'RS', 'logo_url': '/logos/teams/zapatista.png', 'banner_url': '/banners/teams/zapatista.png', 'description': 'Equipe com forte perspectiva política e comunitária.', 'stadium_name': 'Campo Zapatista', 'president_name': 'Yuri Castro', 'coach_name': 'Levi Silva', 'created_at': '2023-01-08T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '32', 'league_id': 'l1', 'name': 'IV:XX de Novembro', 'slug': 'ivxx-de-novembro', 'colors': '#a855f7', 'secondary_color': '#7e22ce', 'abbreviation': 'IVX', 'founded_year': 2022, 'city': 'Curitiba', 'state': 'PR', 'logo_url': '/logos/teams/ivxx-de-novembro.png', 'banner_url': '/banners/teams/ivxx-de-novembro.png', 'description': 'Time com forte presença histórica e identidade de bairro.', 'stadium_name': 'Arena IV:XX', 'president_name': 'Rita Franco', 'coach_name': 'Henrique Luz', 'created_at': '2022-02-22T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '33', 'league_id': 'l1', 'name': 'Aqui Estamos', 'slug': 'aqui-estamos', 'colors': '#fbbf24', 'secondary_color': '#d97706', 'abbreviation': 'AQE', 'founded_year': 2022, 'city': 'Curitiba', 'state': 'PR', 'logo_url': '/logos/teams/aqui-estamos.png', 'banner_url': '/banners/teams/aqui-estamos.png', 'description': 'Time que representa a presença constante e organizada da LFA.', 'stadium_name': 'Campo Aqui Estamos', 'president_name': 'Lúcia Mendes', 'coach_name': 'Breno Nascimento', 'created_at': '2022-04-27T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
        {'id': '34', 'league_id': 'l1', 'name': 'Imperial RSports', 'slug': 'imperial-rsports', 'colors': '#fb923c', 'secondary_color': '#c2410c', 'abbreviation': 'IMP', 'founded_year': 2023, 'city': 'Porto Alegre', 'state': 'RS', 'logo_url': '/logos/teams/imperial-rsports.png', 'banner_url': '/banners/teams/imperial-rsports.png', 'description': 'Equipe de forte presença ofensiva e tradição recente na LFA.', 'stadium_name': 'Arena Imperial', 'president_name': 'Diego Mello', 'coach_name': 'Felipe Tamagno', 'created_at': '2023-06-02T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z', 'is_active': True},
    ]
})

write_json('players.json', {
    'players': [
        {'id': 'p1', 'team_id': '1', 'name': 'Gui', 'number': 9, 'position': 'Atacante', 'birth_date': '1998-03-12', 'nationality': 'Brasileiro', 'height_cm': 180, 'weight_kg': 76, 'dominant_foot': 'direito', 'biography': 'Atacante técnico e decisivo nas grandes partidas.', 'avatar_url': '/avatares/players/gui.png', 'status': 'active', 'joined_date': '2020-03-15T00:00:00Z', 'created_at': '2020-03-15T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z'},
        {'id': 'p2', 'team_id': '1', 'name': 'Cauan', 'number': 7, 'position': 'Meia', 'birth_date': '1999-06-10', 'nationality': 'Brasileiro', 'height_cm': 176, 'weight_kg': 72, 'dominant_foot': 'esquerdo', 'biography': 'Meia criativo com visão de jogo.', 'avatar_url': '/avatares/players/cauan.png', 'status': 'active', 'joined_date': '2020-05-02T00:00:00Z', 'created_at': '2020-05-02T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z'},
        {'id': 'p3', 'team_id': '2', 'name': "N'tcho Sá", 'number': 11, 'position': 'Atacante', 'birth_date': '1997-07-19', 'nationality': 'Brasileiro', 'height_cm': 175, 'weight_kg': 71, 'dominant_foot': 'direito', 'biography': 'Atacante versátil e forte finalizador.', 'avatar_url': '/avatares/players/ntcho-sa.png', 'status': 'active', 'joined_date': '2020-07-14T00:00:00Z', 'created_at': '2020-07-14T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z'},
        {'id': 'p4', 'team_id': '6', 'name': 'John', 'number': 10, 'position': 'Atacante', 'birth_date': '1996-01-25', 'nationality': 'Brasileiro', 'height_cm': 178, 'weight_kg': 74, 'dominant_foot': 'direito', 'biography': 'Jogador de grande presença ofensiva.', 'avatar_url': '/avatares/players/john.png', 'status': 'active', 'joined_date': '2019-08-20T00:00:00Z', 'created_at': '2019-08-20T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z'},
        {'id': 'p5', 'team_id': '7', 'name': 'JR', 'number': 8, 'position': 'Meia', 'birth_date': '1995-11-04', 'nationality': 'Brasileiro', 'height_cm': 174, 'weight_kg': 70, 'dominant_foot': 'direito', 'biography': 'Meia muito técnico e um dos grandes nomes da competição.', 'avatar_url': '/avatares/players/jr.png', 'status': 'active', 'joined_date': '2019-04-20T00:00:00Z', 'created_at': '2019-04-20T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z'},
        {'id': 'p6', 'team_id': '7', 'name': 'Marion', 'number': 13, 'position': 'Atacante', 'birth_date': '1998-09-01', 'nationality': 'Brasileiro', 'height_cm': 181, 'weight_kg': 77, 'dominant_foot': 'esquerdo', 'biography': 'Atacante com finalização precisa e grande presença na área.', 'avatar_url': '/avatares/players/marion.png', 'status': 'active', 'joined_date': '2020-01-11T00:00:00Z', 'created_at': '2020-01-11T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z'},
        {'id': 'p7', 'team_id': '7', 'name': 'Schmidt', 'number': 5, 'position': 'Zagueiro', 'birth_date': '1997-04-22', 'nationality': 'Brasileiro', 'height_cm': 183, 'weight_kg': 79, 'dominant_foot': 'direito', 'biography': 'Defensor sólido e decisivo em bolas aéreas.', 'avatar_url': '/avatares/players/schmidt.png', 'status': 'active', 'joined_date': '2020-02-01T00:00:00Z', 'created_at': '2020-02-01T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z'},
        {'id': 'p8', 'team_id': '7', 'name': 'Apolinário', 'number': 9, 'position': 'Atacante', 'birth_date': '1996-10-15', 'nationality': 'Brasileiro', 'height_cm': 179, 'weight_kg': 75, 'dominant_foot': 'direito', 'biography': 'Atacante rápido e muito presente nas decisões.', 'avatar_url': '/avatares/players/apolinario.png', 'status': 'active', 'joined_date': '2019-12-01T00:00:00Z', 'created_at': '2019-12-01T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z'},
        {'id': 'p9', 'team_id': '15', 'name': 'Doug', 'number': 10, 'position': 'Atacante', 'birth_date': '1998-08-08', 'nationality': 'Brasileiro', 'height_cm': 176, 'weight_kg': 73, 'dominant_foot': 'direito', 'biography': 'Artilheiro da competição e grande referência ofensiva.', 'avatar_url': '/avatares/players/doug.png', 'status': 'active', 'joined_date': '2020-03-01T00:00:00Z', 'created_at': '2020-03-01T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z'},
        {'id': 'p10', 'team_id': '15', 'name': 'Jean Thiago Mottin', 'number': 11, 'position': 'Meia', 'birth_date': '1995-05-09', 'nationality': 'Brasileiro', 'height_cm': 178, 'weight_kg': 74, 'dominant_foot': 'esquerdo', 'biography': 'Meia técnico e importante na construção ofensiva.', 'avatar_url': '/avatares/players/jean-thiago-mottin.png', 'status': 'active', 'joined_date': '2019-11-20T00:00:00Z', 'created_at': '2019-11-20T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z'},
        {'id': 'p11', 'team_id': '34', 'name': 'Imperial', 'number': 7, 'position': 'Atacante', 'birth_date': '1997-07-11', 'nationality': 'Brasileiro', 'height_cm': 180, 'weight_kg': 76, 'dominant_foot': 'direito', 'biography': 'Jogador referência do Imperial na campanha recente da LFA.', 'avatar_url': '/avatares/players/imperial.png', 'status': 'active', 'joined_date': '2023-06-10T00:00:00Z', 'created_at': '2023-06-10T00:00:00Z', 'updated_at': '2026-05-21T00:00:00Z'},
    ]
})

write_json('matches.json', {
    'matches': [
        {'id': 'match-001', 'tournament_id': 'comp-001', 'home_team_id': '2', 'away_team_id': '15', 'score_home': 1, 'score_away': 4, 'date': '2025-05-17', 'round': 'Semifinal', 'location': 'Estádio da Liga', 'status': 'finished', 'created_at': '2025-05-17T00:00:00Z', 'updated_at': '2025-05-17T00:00:00Z'},
        {'id': 'match-002', 'tournament_id': 'comp-001', 'home_team_id': '1', 'away_team_id': '7', 'score_home': 3, 'score_away': 3, 'date': '2025-05-10', 'round': 'Semifinal', 'location': 'Campo Cecília', 'status': 'finished', 'created_at': '2025-05-10T00:00:00Z', 'updated_at': '2025-05-10T00:00:00Z'},
        {'id': 'match-003', 'tournament_id': 'comp-001', 'home_team_id': '7', 'away_team_id': '15', 'score_home': 2, 'score_away': 2, 'date': '2025-06-01', 'round': 'Final', 'location': 'Estádio da Liga', 'status': 'finished', 'created_at': '2025-06-01T00:00:00Z', 'updated_at': '2025-06-01T00:00:00Z'},
        {'id': 'match-004', 'tournament_id': 'comp-001', 'home_team_id': '1', 'away_team_id': '2', 'score_home': 4, 'score_away': 1, 'date': '2025-06-08', 'round': 'Disputa pelo 3º lugar', 'location': 'Campo Cecília', 'status': 'finished', 'created_at': '2025-06-08T00:00:00Z', 'updated_at': '2025-06-08T00:00:00Z'},
    ]
})

write_json('media.json', {
    'media': [
        {'id': 'md-001', 'tournament_id': 'comp-001', 'type': 'photo', 'title': 'Final da Taça Cecília 2025 – Apertura', 'description': 'Momento da decisão entre Pé-de-pano e 9-Dedos com resultado decidido nos pênaltis.', 'url': '/media/photos/taca-cecilia-2025-final.jpg', 'thumbnail_url': '/media/photos/thumbnails/taca-cecilia-2025-final.jpg', 'photographer': 'Equipe LFA', 'date': '2025-06-01', 'tags': ['taca-cecilia', 'final', '2025'], 'created_at': '2025-06-02T00:00:00Z', 'updated_at': '2025-06-02T00:00:00Z'},
        {'id': 'md-002', 'tournament_id': 'comp-001', 'type': 'photo', 'title': 'Celebrando o título do Pé-de-pano', 'description': 'Equipe campeã celebra a conquista após a decisão.', 'url': '/media/photos/pe-de-pano-campeao-2025.jpg', 'thumbnail_url': '/media/photos/thumbnails/pe-de-pano-campeao-2025.jpg', 'photographer': 'Equipe LFA', 'date': '2025-06-01', 'tags': ['campeao', 'pedepano', '2025'], 'created_at': '2025-06-02T00:00:00Z', 'updated_at': '2025-06-02T00:00:00Z'},
        {'id': 'md-003', 'tournament_id': 'comp-002', 'type': 'photo', 'title': 'Copa Eric Cantona 2025', 'description': 'Registro da competição em homenagem a Eric Cantona.', 'url': '/media/photos/copa-eric-cantona.jpg', 'thumbnail_url': '/media/photos/thumbnails/copa-eric-cantona.jpg', 'photographer': 'Equipe LFA', 'date': '2025-06-15', 'tags': ['copa', 'cantona', '2025'], 'created_at': '2025-06-16T00:00:00Z', 'updated_at': '2025-06-16T00:00:00Z'},
        {'id': 'md-004', 'tournament_id': 'comp-003', 'type': 'video', 'title': 'Resumo da Taça Cecília 2025 – Clausura', 'description': 'Recapitulação da fase final e da conquista do Imperial.', 'url': '/media/videos/taca-cecilia-2025-clausura.mp4', 'thumbnail_url': '/media/videos/thumbnails/taca-cecilia-2025-clausura.jpg', 'photographer': 'Equipe LFA', 'date': '2025-10-31', 'duration_seconds': 420, 'tags': ['taca-cecilia', 'clausura', '2025'], 'created_at': '2025-11-01T00:00:00Z', 'updated_at': '2025-11-01T00:00:00Z'},
    ]
})

write_json('podiums.json', {
    'podiums': [
        {'id': 'podium-001', 'tournament_id': 'comp-001', 'first_place': {'team_id': '7', 'team_name': 'Pé de Pano'}, 'second_place': {'team_id': '15', 'team_name': '9-Dedos'}, 'third_place': {'team_id': '1', 'team_name': 'CF Estrela Vermelha'}},
        {'id': 'podium-002', 'tournament_id': 'comp-002', 'first_place': {'team_id': '1', 'team_name': 'CF Estrela Vermelha'}, 'second_place': {'team_id': '2', 'team_name': 'Guairacá Futebol Ancestral'}, 'third_place': {'team_id': '7', 'team_name': 'Pé de Pano'}},
        {'id': 'podium-003', 'tournament_id': 'comp-003', 'first_place': {'team_id': '34', 'team_name': 'Imperial RSports'}, 'second_place': {'team_id': '1', 'team_name': 'CF Estrela Vermelha'}, 'third_place': {'team_id': '3', 'team_name': 'Deportivo Oriental'}},
    ]
})

write_json('standings.json', {
    'standings': [
        {'id': 'standing-001', 'tournament_id': 'comp-001', 'team_id': '1', 'position': 1, 'points': 31, 'wins': 10, 'draws': 1, 'losses': 0, 'goals_for': 66, 'goals_against': 23, 'goals_difference': 43},
        {'id': 'standing-002', 'tournament_id': 'comp-001', 'team_id': '2', 'position': 2, 'points': 24, 'wins': 7, 'draws': 3, 'losses': 1, 'goals_for': 41, 'goals_against': 32, 'goals_difference': 9},
        {'id': 'standing-003', 'tournament_id': 'comp-001', 'team_id': '15', 'position': 3, 'points': 22, 'wins': 7, 'draws': 1, 'losses': 3, 'goals_for': 54, 'goals_against': 29, 'goals_difference': 25},
        {'id': 'standing-004', 'tournament_id': 'comp-001', 'team_id': '7', 'position': 4, 'points': 20, 'wins': 6, 'draws': 2, 'losses': 3, 'goals_for': 65, 'goals_against': 30, 'goals_difference': 35},
        {'id': 'standing-005', 'tournament_id': 'comp-001', 'team_id': '6', 'position': 5, 'points': 17, 'wins': 5, 'draws': 2, 'losses': 4, 'goals_for': 36, 'goals_against': 43, 'goals_difference': -7},
        {'id': 'standing-006', 'tournament_id': 'comp-001', 'team_id': '5', 'position': 6, 'points': 14, 'wins': 4, 'draws': 2, 'losses': 5, 'goals_for': 39, 'goals_against': 46, 'goals_difference': -7},
        {'id': 'standing-007', 'tournament_id': 'comp-001', 'team_id': '4', 'position': 7, 'points': 12, 'wins': 4, 'draws': 0, 'losses': 7, 'goals_for': 26, 'goals_against': 35, 'goals_difference': -9},
        {'id': 'standing-008', 'tournament_id': 'comp-001', 'team_id': '20', 'position': 8, 'points': 12, 'wins': 4, 'draws': 0, 'losses': 7, 'goals_for': 27, 'goals_against': 40, 'goals_difference': -13},
        {'id': 'standing-009', 'tournament_id': 'comp-001', 'team_id': '34', 'position': 9, 'points': 12, 'wins': 3, 'draws': 3, 'losses': 5, 'goals_for': 44, 'goals_against': 39, 'goals_difference': 5},
        {'id': 'standing-010', 'tournament_id': 'comp-001', 'team_id': '3', 'position': 10, 'points': 10, 'wins': 3, 'draws': 1, 'losses': 7, 'goals_for': 22, 'goals_against': 40, 'goals_difference': -18},
        {'id': 'standing-011', 'tournament_id': 'comp-001', 'team_id': '33', 'position': 11, 'points': 9, 'wins': 2, 'draws': 3, 'losses': 6, 'goals_for': 38, 'goals_against': 50, 'goals_difference': -12},
        {'id': 'standing-012', 'tournament_id': 'comp-001', 'team_id': '8', 'position': 12, 'points': 6, 'wins': 2, 'draws': 0, 'losses': 9, 'goals_for': 19, 'goals_against': 70, 'goals_difference': -51},
    ]
})

write_json('tournaments.json', {
    'tournaments': [
        {'id': 't1', 'league_id': 'l1', 'name': 'Taça Cecília 2025 – Apertura', 'season': 'Apertura 25', 'status': 'finished', 'type': 'league', 'description': 'Edição de 2025 da Taça Cecília.', 'created_at': '2025-01-01T00:00:00Z', 'updated_at': '2025-07-01T00:00:00Z'},
        {'id': 't2', 'league_id': 'l1', 'name': 'Copa Eric Cantona', 'season': 'Apertura 25', 'status': 'finished', 'type': 'cup', 'description': 'Copa dedicada à memória de Eric Cantona.', 'created_at': '2025-01-10T00:00:00Z', 'updated_at': '2025-06-16T00:00:00Z'},
        {'id': 't3', 'league_id': 'l1', 'name': 'Taça Cecília 2025 – Clausura', 'season': 'Clausura 25', 'status': 'finished', 'type': 'league', 'description': 'Segunda edição da Taça Cecília em 2025.', 'created_at': '2025-06-01T00:00:00Z', 'updated_at': '2025-11-01T00:00:00Z'},
        {'id': 't4', 'league_id': 'l1', 'name': 'Taça Cecília 2026 – Apertura', 'season': 'Apertura 26', 'status': 'ongoing', 'type': 'league', 'description': 'Edição atual da Taça Cecília.', 'created_at': '2026-02-01T00:00:00Z', 'updated_at': '2026-05-28T00:00:00Z'},
    ]
})

print('Wiki data imported successfully into JSON datasets.')
